-- 1. Create the messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users(id) not null,
  receiver_id uuid references auth.users(id) not null,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_read boolean default false,
  message_type text default 'text' check (message_type in ('text', 'image', 'audio'))
);

-- 2. Enable RLS
alter table public.messages enable row level security;

-- 3. Policies

-- User can see messages they sent or received
create policy "Users can read their own messages"
  on messages for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

-- User can send messages
create policy "Users can send messages"
  on messages for insert
  with check ( auth.uid() = sender_id );

-- User can update status (e.g. mark as read) of received messages
create policy "Recipients can update messages"
  on messages for update
  using ( auth.uid() = receiver_id );

-- 4. Indexes for performance
create index messages_sender_receiver_idx on messages(sender_id, receiver_id);
create index messages_receiver_sender_idx on messages(receiver_id, sender_id);
